"""fourth migration

Revision ID: 0bcda715f022
Revises: 7c2760a717f8
Create Date: 2022-05-15 10:48:10.181392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcda715f022'
down_revision = '7c2760a717f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
