"""fifth migration

Revision ID: fec8b637c265
Revises: f25ed6b7159f
Create Date: 2022-05-15 11:12:24.776784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec8b637c265'
down_revision = 'f25ed6b7159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post', sa.Text(), nullable=False))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'post')
    # ### end Alembic commands ###
